---
compilerOptions:
  experimentalDecorators: true 
  module: es2015 # For webpack Uglify plugin (See also: https://github.com/webpack/webpack/issues/2972) 
  target: es5 # Ditto 
  sourceMap: true
  types:
  - node
  noImplicitAny: true
  preserveConstEnums: true
  noEmitOnError: true
  noUnusedParameters: true
  noUnusedLocals: true
  removeComments: true
  jsx: react
include:
- "./src/**/*"
exclude:
- node_modules
- dist
- ".test.ts"
- test.ts
